apiVersion: v1
stringData:
  prometheus-additional.yaml: |-
    - job_name: "node-exporter"
      static_configs:
      - targets: ["10.1.7.218:9100"]
      - targets: ["10.1.7.171:9100"]
      - targets: ["10.1.7.129:9100"]
      - targets: ["10.1.7.180:9100"]

    - job_name: "etcd-ha"
      static_configs:
      - targets: ["10.1.7.171:2379"]
      - targets: ["10.1.7.129:2379"]
      - targets: ["10.1.7.180:2379"]
    - job_name: "etcd-baremetal"
      static_configs:
      - targets: ["10.1.7.218:2379"]

kind: Secret
metadata:
  name: additional-scrape-configs
