apiVersion: v1
stringData:
  prometheus-additional.yaml: |-
    - job_name: "node-exporter"
      static_configs:
      - targets: ["10.1.7.218:9100"]

kind: Secret
metadata:
  name: additional-scrape-configs
